language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: setup
      script: cp deploy.example.json deploy.json
    - stage: test
      script: npm run test
      script: npm run test:coverage
      script: npm run lint:all
