language: node_js
node_js:
  - "8"

env:
- WORKING_DIR=token
- WORKING_DIR=marketplace

cache:
  directories:
  - "$WORKING_DIR/node_modules"

before_install: npm i -g npm@6.1.0

install:
- cd $WORKING_DIR
- npm prune
- npm install

jobs:
  allow_failures:
    - env: ALLOW_FAILURE=true
  include:
    - stage: lint
      script: cp deploy.example.json deploy.json; npm run lint:all
      env: ALLOW_FAILURE=true
    - stage: test
      script: cp deploy.example.json deploy.json; npm run test
    - stage: coverage
      script: cp deploy.example.json deploy.json; npm run test:coverage
      env: ALLOW_FAILURE=true
